# Generated by Django 3.2.5 on 2021-07-04 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepartementModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=300, null=True)),
                ('email', models.EmailField(max_length=300)),
                ('telephone', models.CharField(max_length=150)),
                ('description_dept', models.TextField()),
            ],
            options={
                'verbose_name': 'département',
                'verbose_name_plural': 'départements',
            },
        ),
    ]
