# Generated by Django 3.2.5 on 2021-07-06 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('departements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClasseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_classe', models.CharField(max_length=300, null=True)),
                ('description_classe', models.TextField()),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departements.departementmodel')),
            ],
        ),
        migrations.CreateModel(
            name='EtudiantModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=300, null=True)),
                ('last_name', models.CharField(max_length=300, null=True)),
                ('mail_user', models.EmailField(max_length=300, null=True)),
                ('password_user', models.CharField(max_length=300)),
                ('date_of_birth', models.DateField(null=True)),
                ('place_of_birth', models.CharField(max_length=300, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UniteEnseignementModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_ue', models.CharField(max_length=300, null=True, unique=True)),
                ('nom_ue', models.CharField(max_length=300, null=True)),
                ('id_classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departements.classemodel')),
            ],
        ),
        migrations.CreateModel(
            name='MatiereModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_matiere', models.CharField(max_length=300, unique=True)),
                ('nom_matiere', models.CharField(max_length=300)),
                ('coefficient', models.IntegerField(null=True)),
                ('credit_matiere', models.IntegerField(null=True)),
                ('quota_horaire', models.IntegerField(null=True)),
                ('description_matiere', models.TextField(null=True)),
                ('unite_enseignement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departements.uniteenseignementmodel')),
            ],
        ),
        migrations.CreateModel(
            name='InscriptionEleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_scolaire', models.DateField()),
                ('Id_classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departements.classemodel')),
                ('Id_etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departements.etudiantmodel')),
            ],
        ),
        migrations.CreateModel(
            name='EnseignantModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=300, null=True)),
                ('last_name', models.CharField(max_length=300, null=True)),
                ('mail_user', models.EmailField(max_length=300, null=True)),
                ('password_user', models.CharField(max_length=300)),
                ('contact_prof', models.CharField(max_length=150)),
                ('date_adhesion', models.DateField(null=True)),
                ('chef_departement', models.BooleanField(default=False)),
                ('departements', models.ManyToManyField(to='departements.DepartementModel')),
                ('matieres', models.ManyToManyField(to='departements.MatiereModel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
