# Generated by Django 3.2.5 on 2021-07-12 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departements', '0004_auto_20210706_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enseignantmodel',
            name='user',
        ),
    ]
