# Generated by Django 3.2.5 on 2021-07-12 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departements', '0005_remove_enseignantmodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscriptioneleve',
            name='annee_scolaire',
            field=models.DateField(null=True),
        ),
    ]
