# Generated by Django 3.2.5 on 2021-07-12 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departements', '0006_alter_inscriptioneleve_annee_scolaire'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classemodel',
            options={'verbose_name': 'Classe'},
        ),
        migrations.AlterModelOptions(
            name='enseignantmodel',
            options={'verbose_name': 'Enseignant'},
        ),
        migrations.AlterModelOptions(
            name='etudiantmodel',
            options={'verbose_name': 'Etudiant'},
        ),
        migrations.AlterModelOptions(
            name='matieremodel',
            options={'verbose_name': 'Matiere'},
        ),
        migrations.AlterModelOptions(
            name='uniteenseignementmodel',
            options={'verbose_name': "Unité d'Enseignement", 'verbose_name_plural': "Unités d'Enseignement"},
        ),
    ]
