# Generated by Django 3.2.5 on 2021-07-12 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departements', '0007_auto_20210712_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiantmodel',
            name='departement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departements.departementmodel'),
            preserve_default=False,
        ),
    ]
