# Generated by Django 3.2.5 on 2021-07-12 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departements', '0008_etudiantmodel_departement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiantmodel',
            name='departement',
            field=models.CharField(choices=[('GIT', 'GIT'), ('GEM', 'GEM'), ('GC', 'GC'), ('TC', 'TC')], max_length=200, null=True),
        ),
    ]
