# Generated by Django 3.2.5 on 2021-07-12 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departements', '0009_alter_etudiantmodel_departement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='etudiantmodel',
            old_name='departement',
            new_name='depart',
        ),
    ]
