# Generated by Django 3.2.5 on 2021-07-12 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('departements', '0011_auto_20210712_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtudiantModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=300, null=True)),
                ('last_name', models.CharField(max_length=300, null=True)),
                ('mail_user', models.EmailField(max_length=300, null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('place_of_birth', models.CharField(max_length=300, null=True)),
                ('depart', models.CharField(choices=[('GIT', 'GIT'), ('GEM', 'GEM'), ('GC', 'GC'), ('TC', 'TC')], max_length=200, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Etudiant',
            },
        ),
        migrations.DeleteModel(
            name='InscriptionEleve',
        ),
    ]
