# Generated by Django 3.2.5 on 2021-07-14 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departements', '0014_alter_inscriptioneleve_annee_scolaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignantmodel',
            name='chief',
            field=models.CharField(choices=[('GIT', 'GIT'), ('GEM', 'GEM'), ('GC', 'GC'), ('TC', 'TC')], default=None, max_length=200, null=True),
        ),
    ]
