# Generated by Django 3.2.5 on 2021-07-14 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departements', '0015_enseignantmodel_chief'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enseignantmodel',
            name='chief',
            field=models.CharField(choices=[('GIT', 'GIT'), ('GEM', 'GEM'), ('GC', 'GC'), ('TC', 'TC'), ('----', '----')], max_length=200, null=True),
        ),
    ]
