# Generated by Django 3.2.5 on 2021-07-19 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departements', '0016_alter_enseignantmodel_chief'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiantmodel',
            name='ma_classe',
            field=models.CharField(choices=[('TC1', 'TC1'), ('TC2', 'TC2'), ('DIC1', 'DIC1'), ('DIC2', 'DIC2'), ('DIC3', 'DIC3')], max_length=200, null=True),
        ),
    ]
