# Generated by Django 3.2.5 on 2021-07-20 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departements', '0017_etudiantmodel_ma_classe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiantmodel',
            name='user',
        ),
    ]
