# Generated by Django 3.2.5 on 2021-07-20 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departements', '0018_remove_etudiantmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='matieremodel',
            name='classe',
            field=models.CharField(choices=[('GIT', 'GIT'), ('GEM', 'GEM'), ('AERO', 'AERO'), ('GC', 'GC'), ('TC', 'TC')], max_length=200, null=True),
        ),
    ]
