# Generated by Django 3.2.5 on 2021-07-20 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departements', '0019_matieremodel_classe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enseignantmodel',
            name='chief',
            field=models.CharField(choices=[('GIT', 'GIT'), ('GEM', 'GEM'), ('GC', 'GC'), ('AERO', 'AERO'), ('TC', 'TC'), ('----', '----')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='etudiantmodel',
            name='depart',
            field=models.CharField(choices=[('GIT', 'GIT'), ('GEM', 'GEM'), ('GC', 'GC'), ('AERO', 'AERO'), ('TC', 'TC')], max_length=200, null=True),
        ),
    ]
